version: "3.5"

services:
  source.database.io:
    image: thiagobrandam/pgdiff-database
    container_name: source.database.io
    restart: always
    build: .
    env_file:
      - database.env
    ports:
      - 54532:5432
    volumes:
      - ./entrypoints/setup.sh:/docker-entrypoint-initdb.d/setup.sh
      - ./entrypoints/source.sql:/setup.sql

  target.database.io:
    image: thiagobrandam/pgdiff-database
    container_name: target.database.io
    restart: always
    build: .
    env_file:
      - database.env
    ports:
      - 54533:5432
    volumes:
      - ./entrypoints/setup.sh:/docker-entrypoint-initdb.d/setup.sh
      - ./entrypoints/target.sql:/setup.sql

networks:
  default:
    name: pgdiff