require "pg"

module PgDiff; end

require_relative "pgdiff/utils.rb"
require_relative "pgdiff/models/base.rb"
require_relative "pgdiff/models/function_privilege.rb"
require_relative "pgdiff/models/function.rb"
require_relative "pgdiff/models/table_column.rb"
require_relative "pgdiff/models/table_constraint.rb"
require_relative "pgdiff/models/table_index.rb"
require_relative "pgdiff/models/table_option.rb"
require_relative "pgdiff/models/table_privilege.rb"
require_relative "pgdiff/models/table.rb"
require_relative "pgdiff/models/schema.rb"
require_relative "pgdiff/models/view_privilege.rb"
require_relative "pgdiff/models/view.rb"
require_relative "pgdiff/models/enum.rb"
require_relative "pgdiff/models/sequence_privilege.rb"
require_relative "pgdiff/models/sequence.rb"
require_relative "pgdiff/models/domain_constraint.rb"
require_relative "pgdiff/models/domain.rb"
require_relative "pgdiff/catalog.rb"
require_relative "pgdiff/deps.rb"
require_relative "pgdiff/database.rb"